<?php if($this->error_en_formulario){  ?>

    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <div id="respuesta-formulario"></div>
    </div>


<?php }  ?>

<?php
//get form
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>

<?php foreach ($form as $element) { ?>

    <?php if(!$element instanceof Zend\Form\Element\Submit){  ?>
    <?php if(!$element instanceof Zend\Form\Element\Hidden){  ?>

        <div class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
            <span class="col-sm-3 control-label">
                <?php //echo $element->getLabel() ?>
                <?php echo $this->formLabel($element); ?>
            </span>

            <div class="col-sm-9">
                    <?php echo $this->formElement($element);
                    if ($this->formElementErrors($element)) ?>
                    <span >
                        <?php echo $this->formElementErrors($element) ?>
                    </span>
            </div>
        </div>
    <?php }else{  ?>
            <?php //echo $this->formLabel($element); ?>
            <?php echo $this->formElement($element);?>
            
    <?php }  ?>


    <?php }else{  ?>

        <div class="form-group">
            <?php //echo $this->formLabel($element); ?>
            <div class="col-sm-offset-3 col-sm-9">
                <?php echo $this->formElement($element);
                if ($this->formElementErrors($element)) ?>
                <button type="button" class="btn default red" data-dismiss="modal">Cancelar</button>
                <span class="text-danger"><?php echo $this->formElementErrors($element) ?></span>
            </div>
        </div>


    <?php }  ?>
<?php
}
?>

<?php echo $this->form()->closeTag($form); ?>


