<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FormularioObjetos extends \Application\Entity\FormularioObjetos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setOrden($orden)
    {
        $this->__load();
        return parent::setOrden($orden);
    }

    public function getOrden()
    {
        $this->__load();
        return parent::getOrden();
    }

    public function setLabel($label)
    {
        $this->__load();
        return parent::setLabel($label);
    }

    public function getLabel()
    {
        $this->__load();
        return parent::getLabel();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setObjectType($objectType)
    {
        $this->__load();
        return parent::setObjectType($objectType);
    }

    public function getObjectType()
    {
        $this->__load();
        return parent::getObjectType();
    }

    public function setSize($size)
    {
        $this->__load();
        return parent::setSize($size);
    }

    public function getSize()
    {
        $this->__load();
        return parent::getSize();
    }

    public function setMaxlength($maxlength)
    {
        $this->__load();
        return parent::setMaxlength($maxlength);
    }

    public function getMaxlength()
    {
        $this->__load();
        return parent::getMaxlength();
    }

    public function setValue($value)
    {
        $this->__load();
        return parent::setValue($value);
    }

    public function getValue()
    {
        $this->__load();
        return parent::getValue();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setReadonly($readonly)
    {
        $this->__load();
        return parent::setReadonly($readonly);
    }

    public function getReadonly()
    {
        $this->__load();
        return parent::getReadonly();
    }

    public function setOndimamic($ondimamic)
    {
        $this->__load();
        return parent::setOndimamic($ondimamic);
    }

    public function getOndimamic()
    {
        $this->__load();
        return parent::getOndimamic();
    }

    public function setDisabled($disabled)
    {
        $this->__load();
        return parent::setDisabled($disabled);
    }

    public function getDisabled()
    {
        $this->__load();
        return parent::getDisabled();
    }

    public function setTipoValidacion($tipoValidacion)
    {
        $this->__load();
        return parent::setTipoValidacion($tipoValidacion);
    }

    public function getTipoValidacion()
    {
        $this->__load();
        return parent::getTipoValidacion();
    }

    public function setRequired($required)
    {
        $this->__load();
        return parent::setRequired($required);
    }

    public function getRequired()
    {
        $this->__load();
        return parent::getRequired();
    }

    public function setClass($class)
    {
        $this->__load();
        return parent::setClass($class);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function setCampos($campos)
    {
        $this->__load();
        return parent::setCampos($campos);
    }

    public function getCampos()
    {
        $this->__load();
        return parent::getCampos();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setErrorMessage($errorMessage)
    {
        $this->__load();
        return parent::setErrorMessage($errorMessage);
    }

    public function getErrorMessage()
    {
        $this->__load();
        return parent::getErrorMessage();
    }

    public function setPlaceholder($placeholder)
    {
        $this->__load();
        return parent::setPlaceholder($placeholder);
    }

    public function getPlaceholder()
    {
        $this->__load();
        return parent::getPlaceholder();
    }

    public function setFormParam(\Application\Entity\FormularioParametros $formParam = NULL)
    {
        $this->__load();
        return parent::setFormParam($formParam);
    }

    public function getFormParam()
    {
        $this->__load();
        return parent::getFormParam();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'orden', 'label', 'name', 'objectType', 'size', 'maxlength', 'value', 'title', 'readonly', 'ondimamic', 'disabled', 'tipoValidacion', 'required', 'class', 'campos', 'estado', 'errorMessage', 'placeholder', 'formParam');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__setInitialized()
	 */
	public function __setInitialized($initialized) {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__setInitializer()
	 */
	public function __setInitializer(\Closure $initializer = null) {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__getInitializer()
	 */
	public function __getInitializer() {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__setCloner()
	 */
	public function __setCloner(\Closure $cloner = null) {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__getCloner()
	 */
	public function __getCloner() {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties()
	 */
	public function __getLazyProperties() {
		// TODO Auto-generated method stub
		
	}

}