<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Perfil extends \Application\Entity\Perfil implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setIdAplicacion($idAplicacion)
    {
        $this->__load();
        return parent::setIdAplicacion($idAplicacion);
    }

    public function getIdAplicacion()
    {
        $this->__load();
        return parent::getIdAplicacion();
    }

    public function setOrden($orden)
    {
        $this->__load();
        return parent::setOrden($orden);
    }

    public function getOrden()
    {
        $this->__load();
        return parent::getOrden();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setSigla($sigla)
    {
    	$this->__load();
    	return parent::setSigla($sigla);
    }
    
    public function getSigla()
    {
    	$this->__load();
    	return parent::getSigla();
    }
    
    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'idAplicacion', 'orden', 'estado','sigla');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__setInitialized()
	 */
	public function __setInitialized($initialized) {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__setInitializer()
	 */
	public function __setInitializer(\Closure $initializer = null) {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__getInitializer()
	 */
	public function __getInitializer() {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__setCloner()
	 */
	public function __setCloner(\Closure $cloner = null) {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__getCloner()
	 */
	public function __getCloner() {
		// TODO Auto-generated method stub
		
	}

	/* (non-PHPdoc)
	 * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties()
	 */
	public function __getLazyProperties() {
		// TODO Auto-generated method stub
		
	}

}