<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2.css"/>
<link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2-metronic.css"/>
<link rel="stylesheet" href="/assets/plugins/data-tables/DT_bootstrap.css"/>
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN THEME STYLES -->
<link href="/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
<link href="/assets/css/custom.css" rel="stylesheet" type="text/css"/>

<div class="row">
				<div class="col-md-12">
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-globe"></i>Lista de Perfiles
							</div>
							<div class="tools">
								<a href="javascript:;" class="collapse">
								</a>
								<a href="#portlet-config" data-toggle="modal" class="config">
								</a>
								<a href="javascript:;" class="reload">
								</a>
								<a href="javascript:;" class="remove">
								</a>
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="btn-group">
									<button id="sample_editable_1_new" class="btn green">
									Add New <i class="fa fa-plus"></i>
									</button>
								</div>
								<div class="btn-group pull-right">
									<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
									</button>
									<ul class="dropdown-menu pull-right">
										<li>
											<a href="#">
												 Print
											</a>
										</li>
										<li>
											<a href="#">
												 Save as PDF
											</a>
										</li>
										<li>
											<a href="#">
												 Export to Excel
											</a>
										</li>
									</ul>
								</div>
							</div>

						<table class="table table-striped table-bordered table-hover" id="sample_1">
						<thead>
						  <tr>
<!-- 						  	<th class="table-checkbox"> -->
<!-- 								<input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/> -->
<!-- 							</th> -->
							<th class="text-center">ID</th>
							<th class="text-center">DESCRIPCION</th>
<!-- 							<th class="text-center">RECURSOS</th> -->
							<th class="text-center">USUARIOS</th>
							<th class="text-center">APLICACION</th>
							<th class="text-center">ESTADO</th>
							<th class="text-center">ACCIONES</th>
						  </tr>
						  </thead>
						  <tbody>
						  <?php foreach ($this->listaPerfilesUsuarios as $perfilesUsuarios){
						  	
						  	$perfil = $perfilesUsuarios['perfil'];
						  	$usuarios = $perfilesUsuarios['usuarios'];

						  	$listaUsuarios = "<ol>";
						  	foreach ($usuarios as $usuario){

								$usrIdPersona = 0;
								if($usuario['usrIdPersona']){
									$usrIdPersona = $usuario['usrIdPersona'];
								}	
	
								$sql = "SELECT * FROM v_planilla WHERE id_persona = $usrIdPersona";
								$util = new \Application\Entity\Repositories\UtilsRepository($this->entityManagerSirh);
								$persona = $util->execNativeSql($sql);
								 
								$nombrePersona = "";
								if($persona){
									$persona = $persona[0];
									$nombrePersona = $persona['nombres'] . " ". $persona['paterno'] . " ".$persona['materno'];
								}
								
							
								$listaUsuarios .= "<li>".$nombrePersona ." [".$usuario['usrName']."]</li>";
							}
							$listaUsuarios .= "</ol>";
						  	
							$acciones = "<a href='#' onclick='editar(" . $perfil ['id'] . ")' title='Editar'>Editar</a>";
						  ?>
						  <tr class="odd gradeX">
<!--   								<td> -->
<!-- 									<input type="checkbox" class="checkboxes" value="1"/> -->
<!-- 								</td> -->
							<td><?php echo $perfil['id']?></td>
							<td><?php echo trim($perfil['nombre']) ?></td>
							<!--  <td><?php //echo trim($perfil['nombre']) ?></td>-->
							<td><?php echo $listaUsuarios ?></td>
							<td><?php echo $perfil['idAplicacion'] ?></td>
							<td><?php echo $perfil['estado'] ?></td>
							<td><?php echo $acciones ?></td>
						  </tr>
						  <?php }?>
						  </tbody>
						</table>	
							
							
							
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
			</div>






<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="/assets/plugins/respond.min.js"></script>
<script src="/assets/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/scripts/core/app.js"></script>
<script src="/assets/scripts/custom/table-managed.js"></script>
<script>
jQuery(document).ready(function() {       
   App.init();
   TableManaged.init();
});
</script>


<?php echo YsUIDialog::initWidget('dialogIdSolicitudes','style="display:none" title="Basic dialog"') ?>
<div id="divFormularioSolicitudes"></div>
<?php echo YsUIDialog::endWidget()?>

<script type="text/javascript">
	  		
    function adicionar(){
      var dialog = "<div id='dialogIdFormularioSol'><div id='divFormularioSol'></div></div>";
      $('#content').append(dialog);
		//$('#formIns').load('/application/solicitud/add',
		  $('#divFormularioSol').load('/application/solicitudes/form',
  		  function(response) {
  			jQuery('#dialogIdFormularioSol').wijdialog({	
 				 "captionButtons": {"maximize": {"visible": false},
  	  				 "minimize": {"visible": false},
  	  				 "toggle": {"visible": false},
  	  				 "refresh": {"visible": false},
  	  				 "pin": {"visible": false},
  	  				 "close": {"visible": true}
  	  				 },	
  				"modal": true,
  				"width": 'auto',
  				"height": 'auto',
  				"position": [ "center", "center"],
  				"title":'Adicionar Solicitud ',
  				"buttons": {
  					"Cerrar": function(){
              $("#dialogIdFormularioSol").remove();
              //jQuery(this).wijdialog('close')
              }
  				}
  			});
  		});
    }
    
    function editar(idSolicitud){
        var dialog = "<div id='dialogIdFormularioSol'><div id='divFormularioSol'></div></div>";
        $('#content').append(dialog);
  		//$('#formIns').load('/application/solicitud/add',
  		  $('#divFormularioSol').load('/application/solicitudes/form/'+idSolicitud,
    		  function(response) {
    			jQuery('#dialogIdFormularioSol').wijdialog({	
   				 "captionButtons": {"maximize": {"visible": false},
    	  				 "minimize": {"visible": false},
    	  				 "toggle": {"visible": false},
    	  				 "refresh": {"visible": false},
    	  				 "pin": {"visible": false},
    	  				 "close": {"visible": true}
    	  				 },	
    				"modal": true,
    				"width": 'auto',
    				"height": 'auto',
    				"position": [ "center", "center"],
    				"title":'Adicionar Solicitud ',
    				"buttons": {
    					"Cerrar": function(){
                $("#dialogIdFormularioSol").remove();
                //jQuery(this).wijdialog('close')
                }
    				}
    			});
    		});
      }

 function solInsumo(idSolicitud){
        
		//var dialog = "<div id='dialogSolicitudes'><div id='formSolicitudes'></div></div>";
    	//$('#content').append(dialog);

    
		$('#divFormularioSolicitudes').load('/application/solicitudes/solicitud?'+$.param({'idSolicitud':idSolicitud}),
		  function(response) {
			jQuery('#dialogIdSolicitudes').wijdialog({	
				"modal": true,
				"width": 'auto',
				"height": 'auto',
				"position": [ "center", "center"],
				"title":'Insumos',
				"buttons": {
          		//"Registrar": function(){$("#formOperacionPartida").submit();},
				"Cerrar": function(){jQuery(this).wijdialog('close')}
				}
			});
		});
  }
    
    function actualizarRegistrosSol(){ 
   	 $("#content").load('/application/solicitudes/index');
    }
   // function actualizarRegistrosOperacion(){
   // $("#content").load('/application/solicitud/index');
	
//}
    
    
</script>