<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Entidades\Module'                        => __DIR__ . '/Module.php',
    'Entidades\Controller\IndexController' => __DIR__ . '/src/Entidades/Controller/IndexController.php',
);