<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Aplicaciones\Module'                        => __DIR__ . '/Module.php',
    'Aplicaciones\Controller\IndexController' => __DIR__ . '/src/Aplicaciones/Controller/IndexController.php',
);