<?php

namespace Application\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * FormularioParametrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormularioParametrosRepository extends EntityRepository
{
}
