<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Usuarios\Module'                        => __DIR__ . '/Module.php',
    'Usuarios\Controller\IndexController' => __DIR__ . '/src/Usuarios/Controller/IndexController.php',
);