<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title">"<?php echo $tabla->getNombre(); ?>" - Editar Registro</h4>
</div>
<div class="modal-body">
	<?php echo $this->partial('partial/form-partial', array('form' => $this->form, 'error_en_formulario'=>$this->error_en_formulario)); ?>
</div>

<script src="assets/scripts/custom/form-validation.js"></script>
<!-- END PAGE LEVEL STYLES -->
<script>
jQuery(document).ready(function() {   
   FormValidation.init();
});
</script>


