
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title">"<?php echo $tabla->getNombre(); ?>" - Crear Registro</h4>
</div>
<div class="modal-body">
	<?php echo $this->partial('partial/form-partial', array('form' => $this->form, 'error_en_formulario'=>$this->error_en_formulario)); ?>
</div>


<!-- <script src="assets/scripts/custom/form-validation.js"></script> -->
<!-- END PAGE LEVEL STYLES -->
<script>
jQuery(document).ready(function() {   
  // FormValidation.init();
});

var ajaxEnviar = function (form) {
	//$('#modal_nuevo').modal('hide');
    App.startPageLoading();
    $.ajax({
        type: $(form).attr('method'),
        url: $(form).attr('action'),
        data: $(form).serialize(),
        dataType: "json",
        success: function (data) {
            if(data.respuesta){ 	
                App.startPageLoading();
                jQuery('#content').load('/administracion/index/parametrica');
                App.showMessage(data.mensaje);
            }else{
                App.showMessage(data.mensaje,'ERROR');
            }
            App.stopPageLoading();
        },
        error : function(jqXHR, status, error) {
            App.showMessage('Ocurrio un error al ejecutar la p&aacute;gina.','ERROR');
            App.stopPageLoading();
        },
    });
   // $('#modal_nuevo').html('');
}

var handleFormSector = function() {
    //formSector
    var form1 = $('#formInsumo'); ///onsole.log(form1);
    var error1 = $('.alert-danger', form1);
    var success1 = $('.alert-success', form1); console.log(success1);
//    var _ajax_enviar = function () {
//        var e = window, a = 'inner';
//        if (!('innerWidth' in window)) {
//            a = 'client';
//            e = document.documentElement || document.body;
//        }
//        return {
//            width: e[a + 'Width'],
//            height: e[a + 'Height']
//        }
//    }
    form1.validate({ 
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: false, // do not focus the last invalid input
        ignore: "",
        rules: {
        	precioUnitario: {
                required: true
            }
//            idPartida: {
//            	required: true
//            },
//            descripcion: {
//                required: true
//                //maxlength: 10
//            },
            
        },
        messages: { // custom messages for radio buttons and checkboxes
        		precioUnitario: {
                    required: "Seleccione una opcion"
                },
//                idPartida: {
//                	required: "Seleccione una opcion"
//                },
//                descripcion: {
//                	required: "Debe registrar la descripci&oacute;n"
//                },
            },

        invalidHandler: function (event, validator) { //display error alert on form submit              
            success1.hide();
            error1.show();
            App.scrollTo(error1, -200);
        },

        highlight: function (element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        unhighlight: function (element) { // revert the change done by hightlight
            $(element)
                .closest('.form-group').removeClass('has-error'); // set error class to the control group
        },

        success: function (label) {
            label
                .closest('.form-group').removeClass('has-error'); // set success class to the control group
        },

        submitHandler: function (form) {
            ajaxEnviar(form);
        	//alert("www");
        }
    });
}

handleFormSector();
//ajaxEnviar("#formInsumo");

</script>

<!-- <script type="text/javascript" src="assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script> -->
<!-- <script type="text/javascript" src="assets/plugins/jquery-validation/dist/additional-methods.min.js"></script> -->

