<script>
    jQuery(document).ready(function() {
        $.notific8('OCURRIO UN ERROR AL GUARDAR LOS DATOS.', {
        life: 3000,
        theme: 'ruby',
        sticky: false,
        horizontalEdge: 'top',
        verticalEdge: 'right',
        zindex: 2000
        });
        
        $.notific8('TODO ESTA BIEN', {
        life: 3000,
        theme: 'lime',
        sticky: false,
        horizontalEdge: 'top',
        verticalEdge: 'right',
        zindex: 2000
        });
        
    });
</script>