<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EstructuraOrganizacional\Module'                        => __DIR__ . '/Module.php',
    'EstructuraOrganizacional\Controller\IndexController' => __DIR__ . '/src/EstructuraOrganizacional/Controller/IndexController.php',
);