<!--  <div style="padding: 50px 0 50px 0">-->
<div style="">

<!--     <div class="row"> -->
<!--         <div class="col-md-4 col-md-offset-4"> -->
            <div class="login-panel panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Ingrese sus credenciales</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="usuario" name="usuario" type="text" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Clave" name="password" type="password" value="">
                            </div>
                            <!--<div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Recordarme.
                                </label>
                            </div>-->
                            <input class="btn btn-primary" type="submit" value="Iniciar Sesion" name="iniciar_sesion">
                        </fieldset>
                    </form>
                </div>
            </div>
<!--         </div> -->
<!--     </div> -->
</div>