

<!--<div style="padding: 50px 0 50px 0;">-->

<!--     <div class="row"> -->

<!--         <div class="col-md-4"> -->
<!--         </div> -->
<!--         <div class="col-md-4 col-md-offset-4"> -->
        	<p class="text-center text-danger" style="font-weight: bold;">
             <?php echo $this->messages; ?>
		    </p>

            <div class="login-panel panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Ingrese sus credenciales</h3>
                </div>
                <div class="panel-body">

                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login')));
                    $form->prepare();

                    echo $this->form()->openTag($form); ?>

                    <!--<form role="form" method="post">-->
                        <fieldset>
                            <div class="form-group">
                                <!--<input class="form-control" placeholder="usuario" name="usuario" type="text" autofocus>-->
                                <?php echo $this->formRow($form->get('username')); ?>
                            </div>
                            <div class="form-group">
                                <!--<input class="form-control" placeholder="Clave" name="password" type="password" value="">-->
                                <?php echo $this->formRow($form->get('password')); ?>
                            </div>
                            <div class="checkbox">
                                <label>
                                   <!-- <input name="remember" type="checkbox" value="Remember Me">Recordarme.-->
                                    <?php echo $this->formRow($form->get('rememberme')); ?>
                                </label>
                            </div>
                            <div align="center">
<!--                             	<input class="btn btn-primary btn-lg btn-block" type="submit" value="Iniciar Sesion" name="iniciar_sesion"> -->
	                            <?php echo $this->formRow($form->get('submit')); ?>
                            </div>
                        </fieldset>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
<!--             </div> -->
<!--         </div> -->
<!--     </div> -->
</div>
<div align="right" style="padding: 0 10px 10px 0;">
<?php // view helper
    if ($user = $this->identity()) {
        echo 'Está logueado como: ' . $this->escapeHtml($user->getUsrName());
?>		
 | <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'logout'));?>">Salir</a> 
<?php
    } else {
       // echo 'No logueado';
    }
    
    //echo md5("12345678");
?>



<!-- <p> -->
	<!--<a href="<?php //echo $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'index'));?>">Registrarse</a> |-->  
	<!--<a href="<?php //echo $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>">¿Olvido su contraseña?</a>-->
<!-- </p> -->
</div>