<?php echo $this->doctype(); ?>

<html lang="es">
<head>

    <meta charset="utf-8">
    
   <?php echo $this->headTitle('Ministerio de Economía y Finanzas Públicas')->setSeparator(' - ')->setAutoEscape(false) ?>

   <?php echo $this->headMeta()
		          ->appendName('viewport', 'width=device-width, initial-scale=1.0')
		          ->appendName('description', 'Sistema de Seguridad de Aplicaciones')
		          ->appendName('author', 'Unidad de Tecnologías de Informacion - MEFP')
        		  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    ?>


    
         <!-- Estilos -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/img/favicon-mefp.ico'))
                        //->prependStylesheet($this->basePath() . '/css/style.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        
                        //->prependStylesheet('/css/style.css')
                        ->prependStylesheet('/sb-admin-2/font-awesome-4.1.0/css/font-awesome.min.css')
                        ->prependStylesheet('/sb-admin-2/css/sb-admin-2.css')
                        ->prependStylesheet('/sb-admin-2/css/plugins/dataTables.bootstrap.css')
                        ->prependStylesheet('/sb-admin-2/css/plugins/metisMenu/metisMenu.min.css')
                        ->prependStylesheet('/sb-admin-2/css/bootstrap.css');
        ?>
    
        
  
    	<!-- Scripts -->
        <?php echo $this->headScript()
            // ->prependFile($this->basePath() . '/js/application.js')
             //->prependFile($this->basePath() . '/js/bootstrap.min.js')
            // ->prependFile($this->basePath() . '/js/jquery.min.js')
             ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
             ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
         ?>
        
            <!-- jQuery Version 1.11.0 -->
    <script src="/sb-admin-2/js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/sb-admin-2/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/sb-admin-2/js/plugins/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/sb-admin-2/js/sb-admin-2.js"></script>
    
    <!-- DataTables JavaScript -->
    <script src="/sb-admin-2/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/sb-admin-2/js/plugins/dataTables/dataTables.bootstrap.js"></script>

     <script src="/js/application.js"></script>        
        
        <?php //echo YsConfigAssets::includeAssets("*") ?>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <div style="">
		<?php echo $this->partial('layout/partial-navigation', array('search' => true)); ?>
		</div>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="row">
                    <?php //echo $this->partial('layout/partial-navbar-content', array('' => '')); ?>
            	    <div id="content" class="jumbotron">
                	    <?php echo $this->content; ?>
	    	       	</div>
		        </div>
            </div>
        </div>
        <?php echo $this->partial('layout/partial-footer', array('valor' => '')); ?>
    </div>
    <!-- /#wrapper -->

        <noscript>
            <div align="center" style="color: red">
            ¡Advertencia! JavaScript debe estar habilitado para un correcto funcionamiento de la Aplicaci&oacute;n.
             </div>
        </noscript>

    <!-- jQuery Version 1.11.0 -->
<!--     <script src="/sb-admin-2/js/jquery-1.11.0.js"></script> -->

    <!-- Bootstrap Core JavaScript -->
<!--     <script src="/sb-admin-2/js/bootstrap.min.js"></script> -->

    <!-- Metis Menu Plugin JavaScript -->
<!--     <script src="/sb-admin-2/js/plugins/metisMenu/metisMenu.min.js"></script> -->

    <!-- Custom Theme JavaScript -->
<!--     <script src="/sb-admin-2/js/sb-admin-2.js"></script> -->
<!--     <script src="/js/application.js"></script> -->
<?php //cho YsConfigAssets::includeAssets("*") ?>
</body>

</html>

