
<div class="page-sidebar-wrapper">
		<div class="page-sidebar navbar-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->
			<ul class="page-sidebar-menu" data-auto-scroll="true" data-slide-speed="200">
<!-- 				<li class="sidebar-toggler-wrapper"> -->
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<!-- 					<div class="sidebar-toggler hidden-phone"> -->
<!-- 					</div> -->
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<!-- 				</li> -->
				<li> 
				<p class="text-muted text-capitalize" style="font-weight: bold; padding: 30px 15px 15px 15px;color: #FFFFFF">
                	<?php echo MisLibrerias\DatosSesion::getAplicacion()  ?>
                    </p>
				</li>
				<!--  <li class="sidebar-search-wrapper">-->
					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
<!-- 					<form class="sidebar-search" action="extra_search.html" method="POST"> -->
<!-- 						<div class="form-container"> -->
<!-- 							<div class="input-box"> -->
<!-- 								<a href="javascript:;" class="remove"> -->
<!-- 								</a> -->
<!-- 								<input type="text" placeholder="Search..."/> -->
<!-- 								<input type="button" class="submit" value=" "/> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- 					</form> -->
					<!-- END RESPONSIVE QUICK SEARCH FORM -->
				<!-- </li>-->
				<li class="start ">
					<a href="/">
						<i class="fa fa-home"></i>
						<span class="title">
							Inicio
						</span>
					</a>
				</li>
				<li class="active ">
					<a href="javascript:;">
						<i class="fa fa-bar-chart-o"></i>
						<span class="title">
							Administración
						</span>
<!-- 						<span class="selected"> -->
<!-- 						</span> -->
<!-- 						<span class="arrow open"> -->
<!-- 						</span> -->
					</a>
					<ul class="sub-menu">
 						<li>
                                <a href="/entidades">Entidades</a>
                                </li>
                                <li>
                                    <a href="/estructura-organizacional">Estructura Organizacional</a>
                                </li>
                                <li>
                                    <a href="/aplicaciones">Aplicaciones</a>
                                </li>
                                <li>
                                    <a href="/usuarios">Usuarios</a> 
                                    
                                </li>
                                <li>
<!--                                     <a href="/perfiles">Perfiles</a> -->
                                     <a href="#" onclick="openUrl('',1);">
                                        Perfiles
                                    </a>
                                    
                                </li>
                                <li>
                                    <a href="/parametros">Parametros</a>
                                </li>
                                <li><a href="/formulacion/test/formulario">Formulario Prueba</a></li>
					</ul>
				</li>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>
	
	
<script type="text/javascript">

function openUrl(url,id){
	url = "/administracion/index/enviar/1";
	$("#content").load(url);
}
	
</script>