			<div class="navbar-header navbar-primary" style="">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
			     <a class="brand" href="/">
                <div style="">
                <img src="/img/logo-mefp.jpg" class="img-responsive" alt="Logo MEFP" style="max-width: 35%;height: auto;">
                <?php //echo MisLibrerias\DatosSesion::getNombreEntidad() ?>
                </div>
                <?php //cho MisLibrerias\DatosSesion::getNombreEntidad() ?>
                  
                <?php //echo MisLibrerias\DatosSesion::getAplicacion()  ?>
                </a>                
            </div>