<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin: 0; background-color: #428bca;">


	<!-- logo -->
	<?php echo $this->partial('layout/partial-navbar-header', array('' => '')); ?>
	<!-- /.navbar-header -->

	<!-- menu esquina derecha -->
	<?php echo $this->partial('layout/partial-navbar-right', array('' => '')); ?>
	<!-- /.navbar-top-links -->

	<!-- menu izquierda -->
	<?php echo $this->partial('layout/partial-navbar-sidebar', array('' => '')); ?>
	<!-- /.navbar-static-side -->
	
	
</nav>
