

<div class="panel panel-primary">
	<div class="panel-heading">
		
		<i class="fa fa-user fa-fw"></i> Lista de Usuarios
		<div class="pull-right">
			<div class="btn-group btn-group-xs">
				
				<button type="button" id="idBtnAdicionar" class="btn btn-default" 
						onclick="">
					<span class="fa fa-plus"></span> Adicionar 
				</button>
				
				<button type="button" class="btn btn-default" onclick="adicionarUsuario()">
					<span class="fa fa-align-right"></span> Asignar Perfil 
				</button>
				
				<button type="button" id = "idBtnActualizarListaUsuarios"  class="btn btn-default"
				data-loading-text="Cargando..." >
					<span class="fa fa-refresh"></span> Actualizar
				</button>
			</div>
		</div>


	</div>

	<div class="panel-body">

		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="dataTables-usuarios">
				<thead>
					<tr>
						<th class="text-center">ID</th>
						<th class="text-center">USUARIO</th>
						<th class="text-center">PERFIL</th>
						<th class="text-center">ESTADO</th>
						<th class="text-center">ACCIONES</th>
					</tr>
				</thead>
				<tbody>
			<?php
			foreach ( $this->listaUsuariosPersona as $usuarioPersona ) {
				
				static $contador = 0;
				$contador ++;
				
				$usuario = $usuarioPersona ['usuario'];
				$persona = $usuarioPersona ['persona'];
				
				// $listaUsuarios = "<ol>";
				// foreach ($usuarios as $usuario){
				
				// $usrIdPersona = 0;
				// if($usuario['usrIdPersona']){
				// $usrIdPersona = $usuario['usrIdPersona'];
				// }
				
				// $sql = "SELECT * FROM v_planilla WHERE id_persona = $usrIdPersona";
				// $util = new \Application\Entity\Repositories\UtilsRepository($this->entityManagerSirh);
				// $persona = $util->execNativeSql($sql);
				
				// $nombrePersona = "";
				// if($persona){
				// $persona = $persona[0];
				// $nombrePersona = $persona['nombres'] . " ". $persona['paterno'] . " ".$persona['materno'];
				// }
				
				// $listaUsuarios .= "<li>".$nombrePersona ." [".$usuario['usrName']."]</li>";
				// }
				// $listaUsuarios .= "</ol>";
				
				$nombreCompleto = "";
				if (count ( $persona ) > 0) {
					$persona = $persona [0];
					$nombreCompleto = $persona ['nombres'] . " " . $persona ['paterno'] . " " . $persona ['materno'] . "<br/>[" . $usuario ['usrName'] . "]";
				} else {
					$nombreCompleto = " [" . $usuario ['usrName'] . "]";
				}
				
				$acciones = "<a href='#' onclick='editar(" . $usuario ['usrId'] . ")' title='Editar'>Editar</a>";
				?>
			<tr class="">
						<td class="text-center"><?php echo $contador?></td>
						<td class="text-left"><?php echo $nombreCompleto ?></td>
						<td class="text-left"><?php echo $nombreCompleto ?></td>
						<td class="text-center"><?php echo $usuario['usrActive'] ==1? "VIGENTE": "NO VIGENTE" ?></td>
						<td class="text-center"><?php echo $acciones ?></td>
					</tr>
						  <?php }?>
						  </tbody>
			</table>
		</div>


	</div>

</div>




<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-usuarios').dataTable({
        	"pagingType": "full_numbers",
       		 "language": {
       			 	"sLengthMenu": "_MENU_ registros por página",
    			  	"search": "Buscar: _INPUT_",
   				  	"info": "Mostrando _START_ a _END_ registros de _TOTAL_ entradas",
        			"infoFiltered": " - filtrado _MAX_ registros totales",
     			  	"infoEmpty": "Sin entradas para mostrar",
      				"emptyTable": "Datos no disponibles en esta tabla",
				  	"paginate": {
     	       			"first": "Primero",
     	       			"last": "Ultimo",
     	       			"next": "Siguiente",
     	       			"previous": "Anterior"
     	       	   	}
    			 },
   			 "aLengthMenu": [ 5, 10, 25, 50, 100 ],
    		 
            });
    });


    $('#idBtnAdicionar').click(function () {
        var btn = $(this)
        btn.button('loading')
        
        
		var idModal = "miModal";
		var title = "Formulario Usuarios";
		var idContent = "divContentModal";
	
		openModalBootstrap(idModal,title,idContent)
		//$('#'+idContent).load('/formulacion/test/formulario',function(){btn.button('reset')});
		$('#'+idContent).load('/index/registration',function(){btn.button('reset')});

      });
      
    $('#idBtnActualizarListaUsuarios').click(function () {
        var btn = $(this)
        btn.button('loading')
        
		var idModal = "miModal";
		var title = "Formulario Usuarios";
		var idContent = "content";
	
		$('#'+idContent).load('/usuarios/index');
      });

    
function adicionarUsuario(){

	var idModal = "miModal";
	var title = "Formulario Usuarios";
	var idContent = "divContentModal";
	
	//openModalBootstrap(idModal,title,idContent)
	//$('#'+idContent).load('/formulacion/test/formulario');
	$('#content').load('/usuarios/index');
	
	
}
    
    
</script>
