
<div style="padding: 50px 0 50px 0">

	<div class="row">

		<div class="col-md-5 col-md-offset-3">

			<div class="panel panel-primary">

				<div class="panel-heading">
					<h3 class="panel-title">Por favor, rellene el formulario y pulse el botón.</h3>
				</div>
				<div class="panel-body">

					<?php
					$form = $this->form;
					$form->setAttribute('action', $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'forgotten-password')));
					$form->prepare();
					
					echo $this->form()->openTag($form);
					?>
					<fieldset>
					<div class="form-group">
					<?php echo $this->formRow($form->get('usrEmail'));?>
					</div>
					
					<div class="form-group">
					<?php echo $this->formSubmit($form->get('submit'));?>
					</div>
					
					</fieldset>					
					<?php echo $this->form ()->closeTag(); ?>
				</div>
			</div>
		</div>
	</div>
</div>

<div align="right" style="padding: 0 10px 10px 0;">
	<a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login'));?>">Inicio</a>
</div>