

<div style="padding: 50px 0 50px 0">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
        
        <h1><?php echo sprintf($this->translate('Se envió un correo a %s. Por favor, verifique su bandeja y confirme su registro!'), $usr_email);?></h1>
        </div>
    </div>
</div>
<div align="right" style="padding: 0 10px 10px 0;">
	<a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login'));?>">Inicio</a>
</div>
        