<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Parametros\Module'                        => __DIR__ . '/Module.php',
    'Parametros\Controller\IndexController' => __DIR__ . '/src/Parametros/Controller/IndexController.php',
);